services:
  - type: web
    name: remove-bg-service
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --timeout 180 --workers 1
    autoDeploy: true
    envVars:
      - key: REMBG_HOME
        value: /tmp/.u2net
      - key: OMP_NUM_THREADS
        value: "2"
