services:
  - type: web
    name: remove-bg-service
    runtime: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && python -c \"import os; os.environ['REMBG_HOME']='.u2net'; os.makedirs('.u2net', exist_ok=True); from rembg import new_session; new_session('u2netp')\""
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --timeout 180 --workers 1
    autoDeploy: true
    envVars:
      - key: REMBG_HOME
        value: .u2net
      - key: OMP_NUM_THREADS
        value: "2"
